# Generated by Django 3.1.7 on 2021-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_post_manuscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='manuscript',
            field=models.FileField(upload_to='manuscripts/'),
        ),
    ]
