# Generated by Django 3.1.7 on 2021-03-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('tropic', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editor_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('cv', models.FileField(upload_to='media/cv/')),
            ],
        ),
    ]
