# Generated by Django 3.1.7 on 2021-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviewer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor_request',
            name='cv',
            field=models.FileField(upload_to='Editor_Request/cv/'),
        ),
        migrations.AlterField(
            model_name='reviewer_request',
            name='cv',
            field=models.FileField(upload_to='Reviewer_Request/cv/'),
        ),
    ]
