# Generated by Django 3.1.7 on 2021-04-03 11:39

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('Article_Title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('Paper_Type', models.CharField(max_length=255, verbose_name='Paper Type')),
                ('Subject_and_Category', models.CharField(max_length=255, verbose_name='Subject & Category')),
                ('Abstract', models.CharField(max_length=500)),
                ('paper', models.FileField(upload_to='Submitted_Article/papers/')),
            ],
        ),
    ]
