# Generated by Django 3.1.7 on 2021-04-05 16:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_submitted_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted_paper',
            name='paper_id',
            field=models.CharField(default=main.models.random_string, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='submitted_paper',
            name='Abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submitted_paper',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
