# Generated by Django 3.1.7 on 2021-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210405_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Ultimate', 'Ultimate')], default='Free', max_length=15, verbose_name='Subscription Status'),
        ),
    ]
